name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-deploy: # 작업의 ID
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 현재 GitHub의 코드

      # --- [CI 영역 시작으로 파이썬 설치를 위한 설정부] ---
      - name: Set up Python 3.14.0
        uses: actions/setup-python@v4 # 파이썬 설정 액션 사용
        with:
          python-version: "3.14.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest # 검사 도구 설치
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # --- [CI 영역 끝] ---
      # --- [CD 영역 시작: 도커 이미지 생성] ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Dockerfile을 읽어 이미지를 만들고(Build), 도커 허브로 전송(Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # 현재 위치의 파일을 소스로 사용
          push: true # 빌드 성공 시 자동으로 도커 허브에 업로드
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest" # 이미지 이름표
      # --- [CD 영역 끝: 도커 이미지 생성] ---

      # --- [CD 영역 시작: EC2 실 배포] ---
      # 3. SSH를 통해 EC2 서버에 접속
      # 이후 script에 적힌 명령어들을 순서대로 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          # 접속 성공 후 EC2 안에서 실행할 리눅스 명령어들
          script: |
            # 도커 허브에서 방금 만든 이미지를 내려받기
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest

            # 기존에 돌아가던 구버전 컨테이너를 끄고 삭제
            sudo docker stop fastapi-server || true
            sudo docker rm fastapi-server || true

            # 새 이미지를 8000번 포트로 실행 (-d: 백그라운드 실행)
            sudo docker run -d --name fastapi-server -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest
      # --- [신규 CD 영역 끝: EC2 실 배포] ---``
